version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t app ./app
      - docker tag app:latest 434418371371.dkr.ecr.us-west-2.amazonaws.com/app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 434418371371.dkr.ecr.us-west-2.amazonaws.com/app:latest